app:
  base-url: http://192.168.29.200:10000

server:
  port: 10000

spring:
  application:
    name: blog-application

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:postgresql://192.168.29.200:5433/blogdb
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  threads:
    virtual:
      enabled: true





# File Storage Configuration
file:
  upload-dir: uploads